package amusementparkssystem;
// Generated Jan 12, 2019 11:54:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Child generated by hbm2java
 */
@Entity
@Table(name="child"
    ,catalog="amusementparksdatabase"
)
public class Child  implements java.io.Serializable {


     private Integer childId;
     private Integer childAge;
     private Double childMoney;
     private String childName;
     private Set<Amusementpark> amusementparks = new HashSet<Amusementpark>(0);
     private Set<Facility> facilities = new HashSet<Facility>(0);

    public Child() {
    }

    public Child(Integer childAge, Double childMoney, String childName, Set<Amusementpark> amusementparks, Set<Facility> facilities) {
       this.childAge = childAge;
       this.childMoney = childMoney;
       this.childName = childName;
       this.amusementparks = amusementparks;
       this.facilities = facilities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="childId", unique=true, nullable=false)
    public Integer getChildId() {
        return this.childId;
    }
    
    public void setChildId(Integer childId) {
        this.childId = childId;
    }

    
    @Column(name="childAge")
    public Integer getChildAge() {
        return this.childAge;
    }
    
    public void setChildAge(Integer childAge) {
        this.childAge = childAge;
    }

    
    @Column(name="childMoney", precision=22, scale=0)
    public Double getChildMoney() {
        return this.childMoney;
    }
    
    public void setChildMoney(Double childMoney) {
        this.childMoney = childMoney;
    }

    
    @Column(name="childName", length=45)
    public String getChildName() {
        return this.childName;
    }
    
    public void setChildName(String childName) {
        this.childName = childName;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="childpark", catalog="amusementparksdatabase", joinColumns = { 
        @JoinColumn(name="ChildPark_childId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="ChildPark_parkId", nullable=false, updatable=false) })
    public Set<Amusementpark> getAmusementparks() {
        return this.amusementparks;
    }
    
    public void setAmusementparks(Set<Amusementpark> amusementparks) {
        this.amusementparks = amusementparks;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="childfacility", catalog="amusementparksdatabase", joinColumns = { 
        @JoinColumn(name="ChildFacility_childId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="ChildFacility_facilityId", nullable=false, updatable=false) })
    public Set<Facility> getFacilities() {
        return this.facilities;
    }
    
    public void setFacilities(Set<Facility> facilities) {
        this.facilities = facilities;
    }




}


