package amusementparkssystem;
// Generated Jan 12, 2019 11:54:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Facility generated by hbm2java
 */
@Entity
@Table(name="facility"
    ,catalog="amusementparksdatabase"
)
public class Facility  implements java.io.Serializable {


     private Integer facilityId;
     private Amusementpark amusementpark;
     private String facilityName;
     private Integer facilityMinAge;
     private Set<Child> childs = new HashSet<Child>(0);

    public Facility() {
    }

	
    public Facility(Amusementpark amusementpark) {
        this.amusementpark = amusementpark;
    }
    public Facility(Amusementpark amusementpark, String facilityName, Integer facilityMinAge, Set<Child> childs) {
       this.amusementpark = amusementpark;
       this.facilityName = facilityName;
       this.facilityMinAge = facilityMinAge;
       this.childs = childs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="facilityId", unique=true, nullable=false)
    public Integer getFacilityId() {
        return this.facilityId;
    }
    
    public void setFacilityId(Integer facilityId) {
        this.facilityId = facilityId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AmusementPark_parkId", nullable=false)
    public Amusementpark getAmusementpark() {
        return this.amusementpark;
    }
    
    public void setAmusementpark(Amusementpark amusementpark) {
        this.amusementpark = amusementpark;
    }

    
    @Column(name="facilityName", length=45)
    public String getFacilityName() {
        return this.facilityName;
    }
    
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName;
    }

    
    @Column(name="facilityMinAge")
    public Integer getFacilityMinAge() {
        return this.facilityMinAge;
    }
    
    public void setFacilityMinAge(Integer facilityMinAge) {
        this.facilityMinAge = facilityMinAge;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="childfacility", catalog="amusementparksdatabase", joinColumns = { 
        @JoinColumn(name="ChildFacility_facilityId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="ChildFacility_childId", nullable=false, updatable=false) })
    public Set<Child> getChilds() {
        return this.childs;
    }
    
    public void setChilds(Set<Child> childs) {
        this.childs = childs;
    }




}


