package amusementparkssystem;
// Generated Jan 12, 2019 11:54:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Manager generated by hbm2java
 */
@Entity
@Table(name="manager"
    ,catalog="amusementparksdatabase"
)
public class Manager  implements java.io.Serializable {


     private Integer managerId;
     private String managerName;
     private Double managerSalary;
     private Set<Amusementpark> amusementparks = new HashSet<Amusementpark>(0);

    public Manager() {
    }

    public Manager(String managerName, Double managerSalary, Set<Amusementpark> amusementparks) {
       this.managerName = managerName;
       this.managerSalary = managerSalary;
       this.amusementparks = amusementparks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="managerId", unique=true, nullable=false)
    public Integer getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    
    @Column(name="managerName", length=45)
    public String getManagerName() {
        return this.managerName;
    }
    
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    
    @Column(name="managerSalary", precision=22, scale=0)
    public Double getManagerSalary() {
        return this.managerSalary;
    }
    
    public void setManagerSalary(Double managerSalary) {
        this.managerSalary = managerSalary;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="manager")
    public Set<Amusementpark> getAmusementparks() {
        return this.amusementparks;
    }
    
    public void setAmusementparks(Set<Amusementpark> amusementparks) {
        this.amusementparks = amusementparks;
    }




}


